/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const WordStyle = IDL.Record({
  'italic' : IDL.Bool,
  'bold' : IDL.Bool,
  'color' : IDL.Text,
  'underline' : IDL.Bool,
  'fontFamily' : IDL.Text,
  'fontSize' : IDL.Nat,
});
export const Sentence = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'addedAt' : IDL.Int,
  'wordStyles' : IDL.Vec(IDL.Tuple(IDL.Text, WordStyle)),
});
export const Word = IDL.Record({
  'text' : IDL.Text,
  'style' : WordStyle,
  'addedAt' : IDL.Int,
});
export const Stats = IDL.Record({
  'sessionWords' : IDL.Nat,
  'totalWords' : IDL.Nat,
  'totalSentences' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addSentence' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'addWord' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'addWords' : IDL.Func([IDL.Vec(IDL.Text)], [IDL.Nat], []),
  'deleteSentence' : IDL.Func([IDL.Nat], [], []),
  'deleteWord' : IDL.Func([IDL.Text], [], []),
  'getAllSentences' : IDL.Func([], [IDL.Vec(Sentence)], ['query']),
  'getAllWords' : IDL.Func([], [IDL.Vec(Word)], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'resetSessionCounter' : IDL.Func([], [], []),
  'updateSentenceWordStyle' : IDL.Func([IDL.Nat, IDL.Text, WordStyle], [], []),
  'updateWordStyle' : IDL.Func([IDL.Text, WordStyle], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const WordStyle = IDL.Record({
    'italic' : IDL.Bool,
    'bold' : IDL.Bool,
    'color' : IDL.Text,
    'underline' : IDL.Bool,
    'fontFamily' : IDL.Text,
    'fontSize' : IDL.Nat,
  });
  const Sentence = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'addedAt' : IDL.Int,
    'wordStyles' : IDL.Vec(IDL.Tuple(IDL.Text, WordStyle)),
  });
  const Word = IDL.Record({
    'text' : IDL.Text,
    'style' : WordStyle,
    'addedAt' : IDL.Int,
  });
  const Stats = IDL.Record({
    'sessionWords' : IDL.Nat,
    'totalWords' : IDL.Nat,
    'totalSentences' : IDL.Nat,
  });
  
  return IDL.Service({
    'addSentence' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'addWord' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'addWords' : IDL.Func([IDL.Vec(IDL.Text)], [IDL.Nat], []),
    'deleteSentence' : IDL.Func([IDL.Nat], [], []),
    'deleteWord' : IDL.Func([IDL.Text], [], []),
    'getAllSentences' : IDL.Func([], [IDL.Vec(Sentence)], ['query']),
    'getAllWords' : IDL.Func([], [IDL.Vec(Word)], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'resetSessionCounter' : IDL.Func([], [], []),
    'updateSentenceWordStyle' : IDL.Func(
        [IDL.Nat, IDL.Text, WordStyle],
        [],
        [],
      ),
    'updateWordStyle' : IDL.Func([IDL.Text, WordStyle], [], []),
  });
};

export const init = ({ IDL }) => { return []; };