/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Sentence {
  'id' : bigint,
  'text' : string,
  'addedAt' : bigint,
  'wordStyles' : Array<[string, WordStyle]>,
}
export interface Stats {
  'sessionWords' : bigint,
  'totalWords' : bigint,
  'totalSentences' : bigint,
}
export interface Word {
  'text' : string,
  'style' : WordStyle,
  'addedAt' : bigint,
}
export interface WordStyle {
  'italic' : boolean,
  'bold' : boolean,
  'color' : string,
  'underline' : boolean,
  'fontFamily' : string,
  'fontSize' : bigint,
}
export interface _SERVICE {
  'addSentence' : ActorMethod<[string], bigint>,
  'addWord' : ActorMethod<[string], boolean>,
  'addWords' : ActorMethod<[Array<string>], bigint>,
  'deleteSentence' : ActorMethod<[bigint], undefined>,
  'deleteWord' : ActorMethod<[string], undefined>,
  'getAllSentences' : ActorMethod<[], Array<Sentence>>,
  'getAllWords' : ActorMethod<[], Array<Word>>,
  'getStats' : ActorMethod<[], Stats>,
  'resetSessionCounter' : ActorMethod<[], undefined>,
  'updateSentenceWordStyle' : ActorMethod<
    [bigint, string, WordStyle],
    undefined
  >,
  'updateWordStyle' : ActorMethod<[string, WordStyle], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];