/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Stats {
    sessionWords: bigint;
    totalWords: bigint;
    totalSentences: bigint;
}
export interface Sentence {
    id: bigint;
    text: string;
    addedAt: bigint;
    wordStyles: Array<[string, WordStyle]>;
}
export interface WordStyle {
    italic: boolean;
    bold: boolean;
    color: string;
    underline: boolean;
    fontFamily: string;
    fontSize: bigint;
}
export interface Word {
    text: string;
    style: WordStyle;
    addedAt: bigint;
}
export interface backendInterface {
    addSentence(text: string): Promise<bigint>;
    addWord(text: string): Promise<boolean>;
    addWords(texts: Array<string>): Promise<bigint>;
    deleteSentence(sentenceId: bigint): Promise<void>;
    deleteWord(text: string): Promise<void>;
    getAllSentences(): Promise<Array<Sentence>>;
    getAllWords(): Promise<Array<Word>>;
    getStats(): Promise<Stats>;
    resetSessionCounter(): Promise<void>;
    updateSentenceWordStyle(sentenceId: bigint, wordText: string, style: WordStyle): Promise<void>;
    updateWordStyle(text: string, style: WordStyle): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addSentence(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSentence(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSentence(arg0);
            return result;
        }
    }
    async addWord(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addWord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWord(arg0);
            return result;
        }
    }
    async addWords(arg0: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addWords(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWords(arg0);
            return result;
        }
    }
    async deleteSentence(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSentence(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSentence(arg0);
            return result;
        }
    }
    async deleteWord(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWord(arg0);
            return result;
        }
    }
    async getAllSentences(): Promise<Array<Sentence>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSentences();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSentences();
            return result;
        }
    }
    async getAllWords(): Promise<Array<Word>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWords();
            return result;
        }
    }
    async getStats(): Promise<Stats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return result;
        }
    }
    async resetSessionCounter(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetSessionCounter();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetSessionCounter();
            return result;
        }
    }
    async updateSentenceWordStyle(arg0: bigint, arg1: string, arg2: WordStyle): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSentenceWordStyle(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSentenceWordStyle(arg0, arg1, arg2);
            return result;
        }
    }
    async updateWordStyle(arg0: string, arg1: WordStyle): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWordStyle(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWordStyle(arg0, arg1);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
